### ISSUE TITLE
vta in zcu104

### ISSUE THREAD

**Issue by xiaoliyang1** [xiaoliyang1/test_program_rpc.py#1]
hello !
I meet a problem  like this when i run test_program_rpc.py.

xiaoliyang@xiaoliyang-virtual-machine:~/tvm$ python3 vta/tests/python/pynq/test_program_rpc.py
Traceback (most recent call last):
  File "vta/tests/python/pynq/test_program_rpc.py", line 44, in <module>
    program_rpc_bitstream()
  File "vta/tests/python/pynq/test_program_rpc.py", line 35, in program_rpc_bitstream
    program_fpga(remote, path)
  File "/home/xiaoliyang/tvm/vta/python/vta/rpc_client.py", line 56, in program_fpga
    fprogram(os.path.basename(bitstream))
  File "/home/xiaoliyang/tvm/python/tvm/_ffi/_ctypes/function.py", line 209, in __call__
    raise get_last_ffi_error()
tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /home/xilinx/tvm/build/libtvm_runtime.so(+0x950fc) [0x7fbbbe80fc]
  [bt] (7) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCServerLoop(int)+0xc0) [0x7fbbbe7190]
  [bt] (6) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::ServerLoop()+0x104) [0x7fbbbdd89c]
  [bt] (5) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::HandleUntilReturnEvent(tvm::runtime::TVMRetValue*, bool, tvm::runtime::PackedFunc const*)+0x1b8) [0x7fbbbdd570]
  [bt] (4) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandleNextEvent(tvm::runtime::TVMRetValue*, bool, tvm::runtime::PackedFunc const*)+0x584) [0x7fbbbe3944]
  [bt] (3) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandleRecvPackedSeqArg()+0x14c) [0x7fbbbe2d6c]
  [bt] (2) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::SwitchToState(tvm::runtime::RPCSession::EventHandler::State)+0x320) [0x7fbbbe1c88]
  [bt] (1) /home/xilinx/tvm/build/libtvm_runtime.so(tvm::runtime::RPCSession::EventHandler::HandlePackedCall()+0x300) [0x7fbbbdb748]
  [bt] (0) /home/xilinx/tvm/build/libtvm_runtime.so(+0x280e8) [0x7fbbb7b0e8]
  File "/home/xilinx/tvm/python/tvm/_ffi/_ctypes/function.py", line 72, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/xilinx/tvm/vta/python/vta/exec/rpc_server.py", line 74, in program_fpga
    program_bitstream.bitstream_program(env.TARGET, path)
  File "/home/xilinx/tvm/vta/python/vta/program_bitstream.py", line 52, in bitstream_program
    pynq_bitstream_program(bitstream)
  File "/home/xilinx/tvm/vta/python/vta/program_bitstream.py", line 48, in pynq_bitstream_program
    bitstream.download()
  File "/usr/local/lib/python3.6/dist-packages/pynq/pl.py", line 1945, in download
    fd.write(self.binfile_name)
TVMError: Except caught from RPC call: OSError: [Errno 22] Invalid argument
During handling of the above exception, another exception occurred:

OSError: [Errno 22] Invalid argument

i hope you can me some advice .thank you .I need your help.I need help.

**Comment by imharish63** [comment]
@xiaoliyang1 

Hi i am trying to resolve same issue. Have you resolved

thanks & regards,
Harish

**Comment by fleebeatles** [comment]
@imharish63 
I have similar issue on ZCU104 when deploying VTA. Did you solve the prolblem? 
Thanks.
